### ISSUE TITLE
Can't even start

### ISSUE THREAD

**Issue by ingpk** [berteh/ScribusGenerator#81] opened 2017-04-27 10:46 UTC
Hi,
maybe I'm to ignorant in Python but I cannot handle this:
I start the CLI script on Ubuntu 16 and get

```
peter@kanne:~/scribus_script$ ./ScribusGeneratorCLI.py test.sla 
Traceback (most recent call last):
  File "./ScribusGeneratorCLI.py", line 119, in <module>
    generator = ScribusGenerator(dataObject)
  File "/home/peter/scribus_script/ScribusGeneratorBackend.py", line 63, in __init__
    logging.config.fileConfig(os.path.join(os.path.abspath(os.path.dirname(__file__)), 'logging.conf'))
  File "/usr/lib/python2.7/logging/config.py", line 77, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python2.7/logging/config.py", line 113, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters'
```

Any ideas?

**Comment by berteh** [comment] 2017-04-27 20:46
Hello @ingpk,

Sorry to read you have trouble with this script.
I have no idea why this error occurs for you, as there is indeed a "formatters" section in the logging.conf file, despite what your error message reports.

Could you please try to (download the whole script again)[https://github.com/berteh/ScribusGenerator/archive/master.zip], and let me know if that fixes your problem.

B.

**Comment by berteh** [comment] 2017-05-07 19:50
hello @ingpk.
any feedback to know if that solved your problem? 
I cannot reproduce the problem: works fine for me in Ubuntu.

**Comment by McQueenPL** [comment] 2017-09-19 16:22
@ingpk @berteh  You missed logging.conf file. I reproduced your problem and fixed by copying "logging.conf" to scribus scripts folder. Cheers.

**Comment by berteh** [comment] 2017-11-26 21:49
thanks @McQueenPL  for finding the problem and fixing it.

I close the bug but feel free to re-open it @ingpk  if you still experience the issue with this fix.

**Closed by berteh** 2017-11-26 21:49 UTC

**Comment by mikini** [comment] 2019-03-04 22:02
I'm coming here as a rather rookie Scribus user wanting to do some merging and this also got me. It stems from the very vague installation instructions;

> Download the script and uncompress it anywhere on the local machine. It can be placed with the standard extension scripts. 

If, like me, you don't want to trash system directories you'll want to copy (preferably by soft link, but that somehow doesn't work) only the needed files into /usr/share/scribus/scripts. Doing this for only *.py files and the pic directory will end up with the GUI being shown but bails out like this on generation attempts.

It doesn't look like there is a nice way out of this as [the m_scriptDir variable used by the scripter extension in isn't very flexible](https://github.com/scribusproject/scribus/blob/ec1238dbc3627f707a25fbc36181d67cba6d968d/scribus/scpaths.cpp#L65).

Explaining this a little better in the readme would be good. I'll try to wrap up a PR.
