### ISSUE TITLE
NEXT-RECORD feature can crash

### ISSUE THREAD

**Issue by VynceMontgomery** [berteh/ScribusGenerator#123] opened 2019-01-25 10:09 UTC
when using the `%VAR_NEXT-RECORD%` feature, if the page consumes more records than the file has, it can crash: 

> 02:06:18 - ScribusGenerator - ERROR: 
> error: Traceback (most recent call last):
>   File "/Applications/Scribus.app/Contents/share/scribus/scripts/ScribusGenerator-master/ScribusGeneratorCLI.py", line 148, in <module>
>     generator.run()
>   File "/Applications/Scribus.app/Contents/share/scribus/scripts/ScribusGenerator-master/ScribusGeneratorBackend.py", line 186, in run
>     shiftedElts = self.shiftPagesAndObjects(tmpElt, pagescount, pageheight, vgap, index-1, recordsInDocument, groupscount, objscount, version)
> UnboundLocalError: local variable 'pagescount' referenced before assignment

**Comment by berteh** [comment] 2019-01-25 14:17
That sucks, sorry.
Will check it out 'cause I though I made sure it was not an issue when I added this feature.

**Comment by berteh** [comment] 2019-01-29 22:13
Just checked it, and cannot reproduce the problem. 

could you please try to run the example provided in SG/examples/MonsterCards ? each page consumes 8 data entries, and the last page has thus only 2 cards, leaving the other places mostly empty without crash... at least by me.

Could the error you witness come from elsewhere? or could you share your template and csv file for me to try to reproduce ?

B.

**Comment by VynceMontgomery** [comment] 2019-01-29 23:41
Yes, that consumes more than 8 records total, though.  Try MonsterCards
-from 2 -to 6 and it crashes.

.

**Comment by berteh** [comment] 2019-02-05 21:42
indeed. bug is now fixed, kindly update your SG from last commit. thanks for the bug report.

**Closed** 2019-02-05 21:43 UTC
Labels: active
