### ISSUE TITLE
Upper limit of rows in csv? 

### ISSUE THREAD

**Issue by jhansdorf** [berteh/ScribusGenerator#50] opened 2016-06-28 13:27 UTC
Hi!

I have just begun to fiddle around with the Scribus Generator and so far it works fantastic!

But I have a problem.The csv file that I use is with over 500 rows and when i try to use it in the script I get an error like the one on the attached image. I tested around i little and found that when the data used is a maximum of 35 rows everything works. Any number above that couses the same error.

Is this i limitation of the script, or is there anything a can do to solve this?
I am on win 10 with scribus 1.4.6 and is using the GUI.
![felmeddelande](https://cloud.githubusercontent.com/assets/20187938/16417484/61816e02-3d46-11e6-9c8a-5a63105f3c7d.jpg)

**Comment by jhansdorf** [comment] 2016-06-28 13:37
Hi!

I have just begun to fiddle around with the Scribus Generator and so far it works fantastic!

But I have a problem. I have a csv file with over 500 rows that i like to make playing card from, but when i try I get an error like the one on the attached image. I tested around i little and found that when the data used is a maximum of 35 rows everything works. Any number above that couses the same error.

Is this i limitation of the script, or is there anything a can do to solve this?
I am on win 10 with scribus 1.4.6 and is using the GUI.

![felmeddelande](https://cloud.githubusercontent.com/assets/20187938/16417438/22dda5d0-3d46-11e6-9c2b-6791f8932c80.jpg)

**Comment by berteh** [comment] 2016-06-28 19:32
hi @jhansdorf 

Nice to read you find this script useful.
I have personally used the script with much more than 35 entries, and the test case I just added in the examples (see examples/business_card_long.csv) to get 155 business cards works fine for me on scribus 1.4.5, win 8, and takes about 6 seconds to generate in merged mode.

From the error you report I suspect some character problem, either a hidden character copy-pasted from MSWord, or an ecoding problem (are you using accentuated characters? are you sure your csv file is encoded in UTF-8? what editor do you use to create this csv?)

let's find the cause for this unacceptable behavior ;)
B.

**Comment by berteh** [comment] 2016-06-28 19:35
if your data is not confidential feel free to upload your csv here (gotta rename its extension ".txt" for github to allow it though). I'd look specifically at the rows 35, 36 and 37.

**Comment by jhansdorf** [comment] 2016-06-29 10:37
Thanks for the answer!


It seems that the problem was that my scv was in the wrong format, I changed it to UTF-8 and the cript works through without any error massages. 

However, in the generated scribus file the images fails to appear in some places thoughout and in all cases after around page 320. I have attached the file so you can take a look, but since the piuctures fail to show at different pages each time I try I haven't been able to find anything strange in the file. 

[Uploading kortlista säkerhet som csv.txt…]()

**Comment by berteh** [comment] 2016-06-29 21:34
From your description of this image problem it looks to me more like a scribus issue rather than one from the scribus generator script. 

Maybe a lack of memory available to handle all these images at once? if that's the case you can try increasing the RAM or swap of your system... or cropping and resizing (down) your images.

See on related matters: https://wiki.scribus.net/canvas/Images_-_PPI_and_DPI

**Closed by berteh** 2016-06-29 21:34 UTC
Labels: question

**Comment by berteh** [comment] 2016-06-29 21:35
I close the bug for the one in the title is fixed. Kindly let me know if &how you manage to fix the images problem, or if it's something else relating to my script!
