### ISSUE TITLE
No image when merging

### ISSUE THREAD

**Issue by RichardPittet** [berteh/ScribusGenerator#66] opened 2016-11-24 16:53 UTC
Hi,
On windows 10, i tried to merge several pictures in one document.
After merging i have on the .sla file the correct name of the picture in place of variable name, but not the picture (blank).
I have no error messages, all workes perfectly with a .csv made with LibreOffice (it doesn't work with Excel 2013)
Any idea ?

Best regards !

**Comment by berteh** [comment] 2016-11-24 20:30
Hello Richard.

I guess it's a matter of Scribus looking for the pictures in another directory than where they are located. 
Images paths are stored _relatively_ to the location of the _template_ (eg: ../../pics/mypic.jpg).

One possible way to confirm this is the problem is to move your merged sla document in the same folder as your template (input file), then open it with Scribus. If that does solve the issue you can either copy the images to your destination folder (mimicking the relative path/directories if any), or create a symbolic link (if you understand what I mean), or leave the merged document with the template (input).

If that does not solve the issue kindly copy-paste here 2-3 lines of your csv data with the value for the image path... as I'd have to dig a bit further.

hope this helps,
Berteh.

**Comment by RichardPittet** [comment] 2016-11-25 07:50
Thanks a lot Berteh for your help.
I thought this night that it was a pictures path problem, and it is.
Good job, it works perfectly.
Suggestion : Maybe add a pictures path in the dialog box ?

**Comment by berteh** [comment] 2016-12-11 01:56
glad it worked for you.
I don't understand your suggestion: the path to the pictures directory is "collected" automatically from your real picture location. What would you want to add/replace/provide in the dialog box?

**Closed by berteh** 2016-12-11 01:56 UTC
Labels: question

**Comment by RichardPittet** [comment] 2016-12-17 22:18
Hi, i suggested to add the possibility to chose a directory as the Picture directory.
Bedt regards
Envoyé de mon téléphone Windows 10

De : Berteh
Envoyé le :dimanche, 11 décembre 2016 02:56
À : berteh/ScribusGenerator
Cc : RichardPittet; Author
Objet :Re: [berteh/ScribusGenerator] No image when merging (#66)

glad it worked for you.
I don't understand your suggestion: the path to the pictures directory is "collected" automatically from your real picture location. What would you want to add/replace/provide in the dialog box?
