### ISSUE TITLE
--single overlapps pages

### ISSUE THREAD

**Issue by MparkG** [berteh/ScribusGenerator#218] opened 2023-12-06 13:31 UTC
i combine 4 instances of a sla document with a csv file.
the sla document has 2 pages.
the resulting document has 8 pages, correctly.
however the instances are merged like this:
all instances content pages:
```
instance 1: 1, 2
instance 2: 3, 4
instance 3: 5, 6
instance 4: 7, 8
```

into single document like this:
```
PAGE:                       1     2      3      4      5     6       7        8
content page of instances:  1     2,3    4,5    6,7    8     empty   empty    empty
                                                             page    page     page
```

**Comment by berteh** [comment] 2024-08-08 19:54
sorry for late reply.

I cannot reproduce your issue, as illustrated in the attached file where I created a 2 pages template file with 
document setup > properties > layout > facing pages; then moved any wanted item on the appropriate page, with a NEXT-RECORD tag on all following entries but the first 1... and ran the ScribusGenerator in merged mode.

could you maybe attach your SLA template if you still haven't solved your issue ?
thanks.

[multipages.zip](https://github.com/user-attachments/files/16552775/multipages.zip)

**Comment by bjoluc** [comment] 2024-12-18 19:58
I think @MparkG's document did – like my repro – neither have facing pages nor a NEXT-RECORD tag. @berteh Your `multipages.zip` example breaks when you remove the `NEXT-RECORD` tag and switch to single pages. Originally, I hit this issue with a four-page facing-pages template without `NEXT-RECORD`.

The root cause seems to be that `vertical_offset` is not multiplied by the number of single pages/facing page pairs per template. This only becomes an issue when one record fills more than one single page or more than two facing pages. I'll submit a PR shortly :slightly_smiling_face:

**Closed** 2024-12-25 15:24 UTC
Labels: cannot reproduce
