### ISSUE TITLE
Cannot include csv when a field contains a "lower than" (<) sign 

### ISSUE THREAD

**Issue by Gullumluvl** [berteh/ScribusGenerator#80] opened 2017-04-14 14:56 UTC
Hi, thanks again for this plugin that saved me hours of work.

I have a csv file in which some text fields contain '<' signs (scientific abstracts). `ScribusGeneratorCLI.py` fails to generate any output in that case, and the error is not very explicit:

    16:06:16 - ScribusGenerator - INFO: ScribusGenerator initialized
    16:06:16 - ScribusGenerator - INFO: Generating all files for posters_template_2pages.sla in directory .
    16:06:16 - ScribusGenerator - INFO: parsing scribus source file posters_template_2pages.sla
    16:06:16 - ScribusGenerator - INFO: parsing data source file posters_invivo.csv
    16:06:16 - ScribusGenerator - INFO: source document consumes 2 data record(s).
    16:06:16 - ScribusGenerator - ERROR: 
    error: Traceback (most recent call last):
      File "/home/gui0m/.local/share/scribus/ScribusGenerator/ScribusGeneratorCLI.py", line 148, in <module>
        generator.run()
      File "/home/gui0m/.local/share/scribus/ScribusGenerator/ScribusGeneratorBackend.py", line 183, in run
        tmpElt = ET.fromstring(outContent).find('DOCUMENT')
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
        parser.feed(text)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
        self._raiseerror(v)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
        raise err
    ParseError: not well-formed (invalid token): line 1, column 27299

I tried escaping this character with a backslash, but it doesn't work.

I know this character can cause conflict because `.sla` files are xml, but isn't it possible to pass it as raw text?

Thanks a lot!

**Comment by berteh** [comment] 2017-04-15 16:56
thanks for the issue report. will look into it in the next days.

**Comment by VynceMontgomery** [comment] 2019-01-15 03:10
This seems likely to be an encoding issue. Since the .sla is an XML format, variable output should probably be encoded (e.g. with python's xml.sax.utils.escape module).

**Comment by JanPokorny** [comment] 2021-02-16 22:39
Confirmed, issue still exists (on branch python3)

**Comment by berteh** [comment] 2021-03-08 22:58
fixed with MUCH delay in both master and python3 version, sorry for having forgotten about this issue.

**Closed** 2021-03-08 22:57 UTC
Labels: bug
