### ISSUE TITLE
Issue with GROUPS of elements, which are not placed on each page…

### ISSUE THREAD

**Issue by something-strange-to-eat** [berteh/ScribusGenerator#89] opened 2017-06-16 22:59 UTC
When I have a group of elements (e.g. two grouped text frames) in the template, then these groups are not child elements of each but, but all groups belong to the "top" page and therefore get deleted from all pages when the top page get's deleted.

Is this reproduceable or does anyone get groups to work properly?

Thanks in advance and thanks your work!

edit: To be clear; the grouped elements appear on every site, just as you would expect, but they all "belong" to one site only.

**Comment by berteh** [comment] 2017-11-26 22:24
I cannot reproduce. Could you please attach a problematic SLA file or describe the steps to create one ?

**Comment by berteh** [comment] 2018-04-22 02:12
closing issue for lack of answer. @something-strange-to-eat kindly reopen if you still experience the problem and want help fixing it.

**Closed by berteh** 2018-04-22 02:12 UTC
